version: "3.7"

services:
    filebrowser:
        image: filebrowser/filebrowser:pi
        container_name: filebrowser
        volumes:
            - ./files:/srv
        ports:
            - 100:80